### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by LiarOnce** [GameMakerDiscord/Gamemaker-Rubber#3]
I output this error when I am ready to test after installation.
```
$ rubber -v
X:\Users\LiarOnce.DESKTOP-NRV42PI\AppData\Roaming\npm\node_modules\gamemaker-rubber\out\rubber.js:20
    const asyncRun = async () => {
                           ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (X:\Users\LiarOnce.DESKTOP-NRV42PI\AppData\Roaming\npm\node_modules\gamemaker-rubber\out\cli.js:8:16)
    at Module._compile (module.js:541:32)
```

**Comment by paperclover** [comment]
Whats your nodejs version? forgot that I use async functions, which might not be supported on that version of node. Try updating it for now, ill try to get it to work on the lower version of node.

**Comment by LiarOnce** [comment]
I used an older version before, now I can use it after updating the node version.
